name: flutter-macos

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "请输入打包的类型，默认profile 支持profile,release"
        required: true
        default: "profile"
        type: string

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 更新代码
        uses: actions/checkout@v3

      - name: 安装node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: npm install
      - run: npm run tauri build

      - name: 上传macos Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos.dmg
          path: dist/${{ github.event.inputs.version }}+${{ github.event.inputs.code }}/macos.dmg
