name: flutter-windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: "请输入版本，默认1.0.0"
        required: true
        default: "1.0.0"
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 更新代码
        uses: actions/checkout@v3

      - name: 安装node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: npm install
      - run: npm run tauri build

      - name: 上传macos Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Res Browser_${{ github.event.inputs.version }}_x64_en-US.msi
          path: src-tauri\target\release\bundle\msi\Res Browser_${{ github.event.inputs.version }}_x64_en-US.msi
